language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

script: 
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew assembleRelease --info
    - ./gradlew codeCoverageReport

after_success:
    - bash <(curl -s https://codecov.io/bash)

